version: "3.9"

x-networks: &networks
  networks:
    - frontend

networks:
  frontend:
    name: kingmaker-data-web

services:
  app:
    image: hdwhub/kingmaker-data-web:latest
    ports:
      - 3043:80
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.25"
          memory: 400MB
      restart_policy:
        condition: on-failure
    <<: *networks
